#!/bin/sh /etc/rc.common

START=98
STOP=05
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/accessio daemon
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_append_param command verbose
	procd_close_instance
}
