name: master-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pack luci-app-access.ipk
        uses: resmh/action-packipk@master
        with:
          pkgname: luci-app-access
          pkgrepo: 1
          pkggpgrepokey: ${{ secrets.GPGREPOKEY }}
          pkgsignifyrepokey: ${{ secrets.SIGNIFYREPOKEY }}
      
      - name: Release luci-app-access.ipk
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automated Release"
          files: |
            luci-app-access.ipk
            Packages
            Packages.asc
            Packages.sig
            luci_app_access.gpg.pub
            luci_app_access.signify.pub
